apiVersion: v1
kind: PersistentVolume
metadata:
  name: chillingmc-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  claimRef:
    name: chillingmc-pvc-chillingmc-0
    namespace: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath: 
    path: {{ .Values.volumePath }}
