apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chillingmc-server-manager
  namespace: chillingmc
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "patch", "update"]
