apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: global-postgres
  namespace: postgres
  labels:
    app: postgres
    resource-type: global

spec:
  serviceName: global-postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        node-role: pg-store
      volumes:
        - name: pg-pvc
          persistentVolumeClaim:
            claimName:  postgres-pvc
      containers:
        - name: postgres
          image: postgres:18
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: PGDATA
              value: /var/lib/postgresql/data/18/docker/
          volumeMounts:
            - name: pg-pvc
              mountPath: /var/lib/postgresql/data

