apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: postgres
  labels:
    resource-type: global
spec:
  type: ClusterIP
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432
