apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api
  labels:
    app: api-nightfall-is-a-dev
spec:
  replicas: 1
  nodeSelector: {{ .Values.nodes.api }}
  selector:
    matchLabels:
      app: api-nightfall-is-a-dev
  templates:
    containers:
      - name: api-nightfall-is-a-dev
        image: {{ .Values.images.api }}
        env:
          - name: DATABASE_USER
            value: {{ .Values.db.user }}

          - name: DATABASE_PASSWORD
            value: {{ .Values.db.password }}

          - name: DATABASE_HOST
            value: {{ .Values.db.user }}

          - name: DATABASE_PORT
            value: {{ .Values.db.user }}

          - name: DATABASE_NAME
            value: {{ .Values.db.name }}
