apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightfall-is-a-dev
  labels:
    app: nightfall-is-a-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nightfall-is-a-dev
  template:
    metadata:
      labels:
        app: nightfall-is-a-dev
    spec:
      containers:
        - name: nightfall-is-a-dev
          image: {{ .Values.images.cms }}

      
